### ISSUE TITLE
 Is it possible to see the config key with which a user connects?

### ISSUE THREAD

**Issue by diegoara96** [lucaboesch/moodle-quizaccess_safeexambrowser#11]
Hello, we have the need to use 2 config keys and we want to check which user connects to each one in the registry. Is this possible ?

**Comment by lucaboesch** [comment]
Dear @diegoara96

There is no logging code built in in this quiz accessrule plugin. So I'm afraid you won't probably find any logs (i assume that's what you are referring to when mentioning 'registry') in the database about which user used what config key.

Best,
Luca
