### ISSUE TITLE
Secure layout is not used in a secure way when using SEB

### ISSUE THREAD

**Issue by stemiwe** [lucaboesch/moodle-quizaccess_safeexambrowser#2]
The new Moodle Boost theme features a dropdown menu for messages, similar to facebook or other social media.

As this can easily be abused for cheating during quizzes, this feature is removed during quizzes by using the secure layout of the theme, by selecting "full-screen popup with some java scrip security" in quiz settings -> browser security.

However, the secure layout is not used if I use SEB, and even if i require both SEB via a browser key, and select "full-screen popup with some java scrip security" in quiz settings -> browser security, it is still not secure, because the quiz will open in a non-maximized popup window that allows switching back to the main moodle window with its message menu easily.

Can the use of the secure theme be implemented in the SEB quiz access rule?

**Comment by lucaboesch** [comment]
I'm fairly sure the secure page layout is used in quizzes with SEB.

**Comment by timhunt** [comment]
Yes, the code that does this is:

https://github.com/moodleou/moodle-quizaccess_safeexambrowser/blob/master/rule.php#L136

and that looks effectively the same as what is in Moodle core:

https://github.com/moodle/moodle/blob/master/mod/quiz/accessrule/securewindow/rule.php#L76

I wonder why it is not working?

**Comment by stemiwe** [comment]
Hhhm, is anyone using boost theme and can verify whether or not its working at their site? 

As I said, for us it works for the "secure pop-up" setting, so the secure layout does not seem to be generally broken for the boost theme in our version (3.2)

**Comment by stemiwe** [comment]
I got it to work, however im not sure what changed - I cant even replicate the non-working state any more right now...

Anyways, going to close this, thanks for all the input
