### ISSUE TITLE
PHP Warning unlink, when installing plugin.

### ISSUE THREAD

**Issue by unicitgit** [lucaboesch/moodle-quizaccess_safeexambrowser#3]
Hello, I know this is a minor issue, installation finishes fine and the plugin works but when I install the plugin I get the following warning.

PHP Warning:  unlink(/moodledata/cache/core_component.php.tmp): No such file or directory in moodle/lib/moodlelib.php on line 9331

I got the warning in 2 different Moodle instances:
3.5.1+ (Build: 20180727) and
3.4.2+ (Build: 20180425)

Thanks

**Comment by timhunt** [comment]
That error is not specifically related to this plugin. It is an error that happens sometimes with any sort of Moodle install/upgrade. I see it all the time. I think you can safely ignore it.
