### ISSUE TITLE
Wrong message display

### ISSUE THREAD

**Issue by aurelienb1** [lucaboesch/moodle-quizaccess_safeexambrowser#5]
Hi Tim,

We think there is wrong message displaying when the user haven't the right exam key.

The plugin displaying two times 

> You must use an approved version of Safe Exam Browser to attempt this quiz. You can download it from {$a->link}.

But in case wehre the student provide wrong key, it's better to display

> You don't have the right SEB file for this exam.

See picture below

![SEB-Error](https://user-images.githubusercontent.com/51001741/66153845-3a049e80-e5ea-11e9-8b09-ffc3d5a72efc.png)

Regard's

**Comment by timhunt** [comment]
It really depends on how you are communicating this to students. The security hash computed includes the executable file, and if you are following recommendations for how to distribute the settings files, then students never see the file themselves, they get the right file from the launch page.

So, I think the string is OK for the general version of the plugin. If it is not right for your context, you can change it using Moodle Language customiation https://docs.moodle.org/37/en/Language_customisation
